apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "annotationlab.fullname" . }}-config
  labels:
    {{- include "annotationlab.labels" . | nindent 4 }}
data:
  ANNOTATIONLAB_DB_USER: {{ .Values.postgresql.postgresqlUsername }}
  ANNOTATIONLAB_DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword }}
  ANNOTATIONLAB_DB_NAME: {{ .Values.postgresql.postgresqlDatabase }}
  ANNOTATIONLAB_DB_HOST: {{ include "annotationlab.postgresql.fullname" . }}
  ANNOTATIONLAB_FULLNAME: {{ include "annotationlab.fullname" . }}
  KEYCLOAK_DB_USER: {{ .Values.keycloak.postgresql.postgresqlUsername }} 
  KEYCLOAK_DB_PASSWORD: {{ .Values.keycloak.postgresql.postgresqlPassword }}
  KEYCLOAK_DB_NAME: {{ .Values.keycloak.postgresql.postgresqlDatabase }}
  KEYCLOAK_DB_HOST: {{ include "annotationlab.keycloak.postgresql.fullname" . }}
  AIRFLOW_DB_USER: {{ .Values.airflow.postgresql.postgresqlUsername }}
  AIRFLOW_DB_PASSWORD: {{ .Values.airflow.postgresql.postgresqlPassword }}
  AIRFLOW_DB_NAME: {{ .Values.airflow.postgresql.postgresqlDatabase }}
  AIRFLOW_DB_HOST: {{ include "annotationlab.airflow.postgresql.fullname" . }}
  KEYCLOAK_REALM_NAME: {{ .Values.configuration.KEYCLOAK_REALM_NAME }}
  NAMESPACE: {{ .Release.Namespace }}
{{- if .Values.ingress.defaultBackend }}
  KEYCLOAK_SERVER_URL: {{ include "annotationlab.keycloak.internal_url" . }}
{{- else }}
  KEYCLOAK_SERVER_URL: {{ include "annotationlab.keycloak.url" . }}
  ANNOTATIONLAB_URL: {{ include "annotationlab.url" . }}
{{- end }}
