{{- if .Values.registryCredentials.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: kubernetesdockerhub
  labels:
    {{- include "annotationlab.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
