apiVersion: v1
kind: Secret
metadata:
  name: {{ include "annotationlab.fullname" . }}-secret
  labels:
    {{- include "annotationlab.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLASK_SECRET_KEY: {{ .Values.configuration.FLASK_SECRET_KEY }}
  KEYCLOAK_CLIENT_ID: {{ .Values.configuration.KEYCLOAK_CLIENT_ID }}
  KEYCLOAK_CLIENT_SECRET_KEY: {{ .Values.configuration.KEYCLOAK_CLIENT_SECRET_KEY }}
  DATABASE_CONNECTION_STRING: {{ include "annotationlab.annotationdb.connectionString" . }}
  AIRFLOW_DB_CONNECTION_STRING: {{ include "annotationlab.airflowdb.connectionString" . }}
