apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/buffering: |
      maxrequestbodybytes: {{ mul .Values.ingress.uploadLimitInMegabytes 1048576 }}
      memrequestbodybytes: {{ mul .Values.ingress.uploadLimitInMegabytes 1048576 }}
  name: {{ include "annotationlab.fullname" . }}
  labels:
    {{- include "annotationlab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "annotationlab.selectorLabels" . | nindent 4 }}
