apiVersion: v1
kind: Service
metadata:
  name: {{ include "annotationlab.fullname" . }}-model-server
  labels:
    {{- include "annotationlab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.model_server.service.type }}
  ports:
  - name: {{ .Values.model_server.service.portName }}
    port: {{ .Values.model_server.service.port }}
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: model-server
    app.kubernetes.io/name: model-server
