{{- if .Values.sharedData.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "annotationlab.fullname" . }}-model-server-data
  labels:
    {{- include "annotationlab.labels" . | nindent 4 }}
spec:
  {{- if .Values.sharedData.storageClass }}
  storageClassName: {{ .Values.sharedData.storageClass }}
  accessModes:
  - ReadWriteMany
  {{- else }}
  accessModes:
  - ReadWriteOnce
  {{- end }}
  resources:
    requests:
      {{- if .Values.sharedData.storageSize }}
      storage: {{ .Values.sharedData.storageSize }}
      {{- else }}
      storage: "5Gi"
      {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "annotationlab.fullname" . }}-shared-image-data
  labels:
    {{- include "annotationlab.labels" . | nindent 4 }}
spec:
  {{- if .Values.sharedData.storageClass }}
  storageClassName: {{ .Values.sharedData.storageClass }}
  accessModes:
  - ReadWriteMany
  {{- else }}
  accessModes:
  - ReadWriteOnce
  {{- end }}
  resources:
    requests:
      {{- if .Values.sharedData.images.storageSize }}
      storage: {{ .Values.sharedData.images.storageSize }}
      {{- else }}
      storage: "5Gi"
      {{- end }}
{{- end -}}
