---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: annotationlab-cronjob
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "create", "list", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: annotationlab-cronjob
subjects:
- kind: ServiceAccount
  name: annotationlab
  namespace: default
roleRef:
  kind: ClusterRole
  name: annotationlab-cronjob
  apiGroup: rbac.authorization.k8s.io
