apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "annotationlab.fullname" . }}-cacert-bundle-script
  labels:
    {{- include "annotationlab.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "annotationlab.fullname" . }}-cacert-bundle-script
      containers:
      - name: init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["/usr/local/bin/python"]
        args: ["/tmp/cacert-bundle-script/script.py"]
        volumeMounts:
          - name: cacert-bundle-script
            mountPath: /tmp/cacert-bundle-script/
      volumes:
        - name: cacert-bundle-script
          configMap:
            name: {{ include "annotationlab.fullname" . }}-cacert-bundle-script
            items:
            - key: script.py
              path: script.py
            - key: cacert.pem
              path: cacert.pem
