apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "annotationlab.fullname" . }}-cacert-bundle-script
  labels:
    {{- include "annotationlab.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "create", "patch"]
