apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "annotationlab.fullname" . }}-cacert-bundle-script
  labels:
    {{- include "annotationlab.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
