version: "2.1"
orbs:
    kube-orb: circleci/kubernetes@0.11.2
    helm: circleci/helm@1.1.1

executors:
  base_image:
    docker:
      - image: circleci/buildpack-deps:stretch

commands:
  # Setting up docker layer caching
  # Logging into ECR
  #
  docker_caching:
    steps:
      - setup_remote_docker:
          version: 19.03.13
  login:
    steps:
      - run:
          name: Login into ECR
          command: docker login -u $MY_USER -p $MY_CRED docker.io
  # Build docker images
  build_image:
    steps:
      - run:
          name: Build Docker Images
          command:  docker build --build-arg code_version=210705-4c3fcd3 --build-arg db-name=mysql  -t bikclu/sample-app:$CIRCLE_SHA1 .
  push_image:
    steps:
      - run:
          name: Push latest Image to ECR
          command: docker push bikclu/sample-app:$CIRCLE_SHA1

jobs:
  build_and_push:
    docker:
    - image:  circleci/buildpack-deps:stretch
    steps:
      - checkout
      - login
      - docker_caching  
      - build_image
      - push_image
      - run:
          name: Update Image tag
          command: |
                   sed "1,/imageTag/s/imageTag: .*/imageTag: ${CIRCLE_SHA1}/g" -i ./myapp-helm-chart/values.yaml
                   git config --global user.email "bikash.bhandari1986@gmail.com"
                   git config --global user.name "Bikash Bhandari"
                   git add ./myapp-helm-chart/values.yaml
                   git commit -m "Updating image tag with latest build number."

workflows:
  version: 2
  build-sample-app:
    jobs:
      - build_and_push:
          context:
           - MY_CRED
          filters:
            branches:
              only:
                - main
