apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "myapp.fullname" . }}-configuration
data:
  my-config.sh: |
                 #!/bin/sh
                 ## wait until MySQL is really available
                 maxcounter=60
                  
                  counter=1
                  while ! mysql --protocol TCP -u"root" -pP@ssw0rd -e "show databases;" > /dev/null 2>&1; do
                      sleep 1
                          counter=`expr $counter + 1`
                              if [ $counter -gt $maxcounter ]; then
                                      >&2 echo "We have been waiting for MySQL too long already; failing."
                                              exit 1
                                                  fi;
                                                  done
