apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysqlRootPassword | b64enc | quote }}
  MYSQL_USER: {{ .Values.mysqluser | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysqlRootPassword | b64enc | quote }}
